### ISSUE TITLE
Rating

### ISSUE THREAD

**Issue by ghoshtapo** [TetraEtc/safygiphy#5]
thanks for this. Is there a way I can pass Rating (pg-13, etc) requirements in the query parameters?

**Comment by StewPoll** [comment]
Thank you for asking! I hope that you've found this library useful.

This is indeed possible. As with any other parameter they specify in [their docs](https://developers.giphy.com/docs/) you can simply add `rating='pg'` into the function.

To extend the initial example from the README:
```python
import safygiphy
g = safygiphy.Giphy()
r = g.random(tag="success", rating="pg")
```

Let me know if you need more assistance

**Comment by ghoshtapo** [comment]
Yeah, I figured that out based on the kwargs params in your init.py. Thanks nevertheless. I am thinking of adding functionality to this to add captions to the GIF

**Comment by StewPoll** [comment]
Closing this issue for now. Feel free to re-open if needed.
